exclude: ^tests/

default_language_version:
    python: python3.11

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [ --branch, dev ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
