"""add nodes, users models

Revision ID: d1a79484eb35
Revises: 
Create Date: 2024-04-08 16:40:42.836647

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1a79484eb35"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("workflows",
                    sa.Column("name", sa.String(), nullable=False),
                    sa.Column("description", sa.String(), nullable=True),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.Column("updated_at", sa.DateTime(), nullable=False),
                    sa.Column("created_by", sa.Uuid(), nullable=True),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_table("nodes",
                    sa.Column("node_type", sa.Enum("start", "message", "condition", "end", name="nodetype"),
                              nullable=False),
                    sa.Column("workflow_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.Column("updated_at", sa.DateTime(), nullable=False),
                    sa.Column("created_by", sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_table("condition_node_configurations",
                    sa.Column("node_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.Column("updated_at", sa.DateTime(), nullable=False),
                    sa.Column("created_by", sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_table("edges",
                    sa.Column("status", sa.Enum("zero", "yes", "no", name="edgeweight"), nullable=False),
                    sa.Column("source_node_id", sa.Uuid(), nullable=False),
                    sa.Column("target_node_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.Column("updated_at", sa.DateTime(), nullable=False),
                    sa.Column("created_by", sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(["source_node_id"], ["nodes.id"], ),
                    sa.ForeignKeyConstraint(["target_node_id"], ["nodes.id"], ),
                    sa.PrimaryKeyConstraint("id"),
                    sa.UniqueConstraint("source_node_id", "target_node_id")
                    )
    op.create_table("end_node_configurations",
                    sa.Column("node_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.Column("updated_at", sa.DateTime(), nullable=False),
                    sa.Column("created_by", sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_table("message_node_configurations",
                    sa.Column("status", sa.Enum("pending", "sent", "opened", name="nodestatus"), nullable=True),
                    sa.Column("text", sa.String(), nullable=False),
                    sa.Column("node_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.Column("updated_at", sa.DateTime(), nullable=False),
                    sa.Column("created_by", sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_table("start_node_configurations",
                    sa.Column("node_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.Column("updated_at", sa.DateTime(), nullable=False),
                    sa.Column("created_by", sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ),
                    sa.PrimaryKeyConstraint("id")
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("start_node_configurations")
    op.drop_table("message_node_configurations")
    op.drop_table("end_node_configurations")
    op.drop_table("edges")
    op.drop_table("condition_node_configurations")
    op.drop_table("nodes")
    op.drop_table("workflows")
    # ### end Alembic commands ###
