name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Run tests and generate coverage report
        run: |
          poetry run coverage run --source=your_module -m pytest
          poetry run coverage report -m > coverage.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.txt

  update-readme:
    name: Update README with coverage results
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: .

      - name: Extract coverage percentage
        id: extract_coverage
        run: |
          coverage=$(awk '/^TOTAL/ {print substr($4, 1, length($4)-1)}' coverage.txt)
          echo "::set-output name=coverage::$coverage"

      - name: Update README
        uses: lowlighter/metrics@latest
        with:
          yaml: |
            README:
              content: |
                Current test coverage: ${{ steps.extract_coverage.outputs.coverage }}%
